language: haskell
ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8
  - 7.9
  - 8.0
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal sandbox init && cabal install hpc-coveralls
  - .cabal-sandbox/bin/hpc-coveralls doctest
