language: haskell
ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8
  - 7.9
  - 8.0
before_script:
  - cabal install hpc-coveralls
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - hpc-coveralls doctest
